name: CI/CD Argo Helm Kubernetes

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'helm/**'

env:
  IMAGE_NAME: krlitos/actividad3-gutierrez

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Configure JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Update image for ArgoCD
        run: |
          sed -i "s/  tag: .*/  tag: \"${{ steps.vars.outputs.IMAGE_TAG }}\"/" helm/patrones-api/Values.yaml
          echo "Nuevo tag_image: ${{ steps.vars.outputs.IMAGE_TAG }}"

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/patrones-api/Values.yaml
          git diff --staged --quiet || git commit -m "auto: update image_tag to ${{ steps.vars.outputs.TAG }}"
          git push origin HEAD:${{ github.head_ref }}